/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HomepageService } from "../homepage.service";
import { HomepageCreateInput } from "./HomepageCreateInput";
import { HomepageWhereInput } from "./HomepageWhereInput";
import { HomepageWhereUniqueInput } from "./HomepageWhereUniqueInput";
import { HomepageFindManyArgs } from "./HomepageFindManyArgs";
import { HomepageUpdateInput } from "./HomepageUpdateInput";
import { Homepage } from "./Homepage";
@swagger.ApiBearerAuth()
export class HomepageControllerBase {
  constructor(
    protected readonly service: HomepageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "Homepage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: Homepage })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: HomepageCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Homepage> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Homepage",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Homepage"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        freedomPay: data.freedomPay
          ? {
              connect: data.freedomPay,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        email: true,

        freedomPay: {
          select: {
            id: true,
          },
        },

        id: true,
        mobileNumber: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "Homepage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [Homepage] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(HomepageFindManyArgs)
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Homepage[]> {
    const args = plainToClass(HomepageFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Homepage",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        email: true,

        freedomPay: {
          select: {
            id: true,
          },
        },

        id: true,
        mobileNumber: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "Homepage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: Homepage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: HomepageWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Homepage | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Homepage",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        email: true,

        freedomPay: {
          select: {
            id: true,
          },
        },

        id: true,
        mobileNumber: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "Homepage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Homepage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: HomepageWhereUniqueInput,
    @common.Body()
    data: HomepageUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Homepage | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Homepage",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Homepage"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          freedomPay: data.freedomPay
            ? {
                connect: data.freedomPay,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          email: true,

          freedomPay: {
            select: {
              id: true,
            },
          },

          id: true,
          mobileNumber: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "Homepage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Homepage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: HomepageWhereUniqueInput
  ): Promise<Homepage | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          email: true,

          freedomPay: {
            select: {
              id: true,
            },
          },

          id: true,
          mobileNumber: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
