/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { HomepageWhereInput } from "./HomepageWhereInput";
import { Type } from "class-transformer";
import { HomepageOrderByInput } from "./HomepageOrderByInput";

@ArgsType()
class HomepageFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => HomepageWhereInput,
  })
  @Field(() => HomepageWhereInput, { nullable: true })
  @Type(() => HomepageWhereInput)
  where?: HomepageWhereInput;

  @ApiProperty({
    required: false,
    type: HomepageOrderByInput,
  })
  @Field(() => HomepageOrderByInput, { nullable: true })
  @Type(() => HomepageOrderByInput)
  orderBy?: HomepageOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { HomepageFindManyArgs };
